const titleStyles = {
  Newbie: "title-newbie",
  Rookie: "title-rookie",
  Player: "title-player",
  Contender: "title-contender",
  Gamer: "title-gamer",
  Challenger: "title-challenger",
  Strategist: "title-strategist",
  Tactician: "title-tactician",
  Prodigy: "title-prodigy",
  Overlord: "title-game-master",
  Arcadian: "title-arcade-ace",
  Puzzler: "title-puzzle-wizard",
  Duelist: "title-digital-duelist",
  Warrior: "title-pixel-warrior",
  Champion: "title-champion",
  Veteran: "title-veteran",
  Grandmaster: "title-grandmaster",
  Legend: "title-gameverse-legend",
  Cosmic: "title-cosmic-controller",
  Bender: "title-reality-bender",
  Supreme: "title-supreme-player",
};

export default titleStyles;
